### ISSUE TITLE
Game Crash When Opening World

### ISSUE THREAD

**Issue by XXFishhXX** [Dysth/Generations#251]
I have previously reported this issue I've been having a few months ago on the Pixelmon Generations Discord, and we were not able to find out what the problem or issue that was causing it was. I have tried many different things but it results in a crash every single time. Personally I believe it has something to do with the Trade Machine model, but i'm not able to know for sure,

Steps to Reproduce:
I have know idea because I do not know what the issue is.

Versions:
Pixelmon v8.5.1, forge v14.23.5.2847

Reports:
Here is the crash report!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EarlyLoadPlugin (PixelmonGenerations-1.12.2-8.5.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/25/21 8:54 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.block.Block.func_185503_a(Block.java:639)
	at net.minecraft.block.Block.func_180636_a(Block.java:631)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:473)
	at net.minecraft.world.World.func_147447_a(World.java:1087)
	at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:491)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1718)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.Block.func_185503_a(Block.java:639)
	at net.minecraft.block.Block.func_180636_a(Block.java:631)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:473)
	at net.minecraft.world.World.func_147447_a(World.java:1087)
	at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:491)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['XX_Fishh_XX'/5, l='MpServer', x=-166.96, y=205.94, z=-359.47]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (56,206,-680), Chunk: (at 8,12,8 in 3,-43; contains blocks 48,0,-688 to 63,255,-673), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 61798738 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 12 total; [EntityPixelmon['Salandit'/17, l='MpServer', x=-167.50, y=218.00, z=-283.50], EntityPixelmon['Salandit'/20, l='MpServer', x=-160.50, y=211.00, z=-294.50], EntityPlayerSP['XX_Fishh_XX'/5, l='MpServer', x=-166.96, y=205.94, z=-359.47], NPCTrainer['Ashton'/8, l='MpServer', x=-209.50, y=168.00, z=-292.50], EntityPixelmon['Salandit'/24, l='MpServer', x=-210.50, y=211.00, z=-282.50], EntityPixelmon['Torkoal'/25, l='MpServer', x=-182.50, y=214.00, z=-314.50], EntityPixelmon['Frillish'/27, l='MpServer', x=-188.50, y=165.00, z=-401.50], NPCTutor['FireBreather'/12, l='MpServer', x=-178.50, y=165.20, z=-446.70], EntityPixelmon['Goldeen'/28, l='MpServer', x=-205.50, y=163.00, z=-417.50], EntityPixelmon['Baltoy'/13, l='MpServer', x=-225.50, y=206.00, z=-312.50], EntityPixelmon['Goldeen'/29, l='MpServer', x=-181.50, y=164.00, z=-420.50], EntityPixelmon['Swirlix'/14, l='MpServer', x=-215.50, y=206.00, z=-336.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1870602376 bytes (1783 MB) / 3196583936 bytes (3048 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                        | Signature |
	|:------ |:----------------- |:------------ |:--------------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                                 | None      |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                                 | None      |
	| LCHIJA | aearlymodloader   | 8.5.1        | minecraft.jar                                 | None      |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2847-universal.jar       | None      |
	| LCHIJA | forge             | 14.23.5.2847 | forge-1.12.2-14.23.5.2847-universal.jar       | None      |
	| LCHIJA | betterswiming     | 1.0.4        | Better-Swiming-Mod-1.12.2.jar                 | None      |
	| LCHIJA | biomesoplenty     | 7.0.1.2444   | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None      |
	| LCHIJA | customnpcs        | 1.12         | CustomNPCs_1.12.2(30Jan19).jar                | None      |
	| LCHIJA | jei               | 4.9.1.168    | jei_1.12.2-4.9.1.168.jar                      | None      |
	| LCHIJA | pixelmon          | 8.5.1        | PixelmonGenerations-1.12.2-8.5.1.jar          | None      |
	| LCHIJA | pixelextras       | 3.3.0        | PixelExtras-UNIVERSAL-8.0.0-3.3.0.jar         | None      |
	| LCHIJA | travelersbackpack | 1.0.33       | TravelersBackpack-1.12.2-1.0.33.jar           | None      |
	| LCHIJA | worldedit         | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar         | None      |

	Loaded coremods (and transformers): 
EarlyLoadPlugin (PixelmonGenerations-1.12.2-8.5.1.jar)
  com.pixelmongenerations.core.plugin.PixelmonTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 462.31' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 462.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 462.31
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

Thank you and I know this is annoying I was just really hoping to be able to get the world I had been working on for a very long time back. Thank you again!

**Comment by Stampede2011** [comment]
@XXFishhXX are you still getting this issue?

**Comment by XXFishhXX** [comment]
I actually managed to fix it by deleting a certain chunk of the world and reopening.
